name: Update README.md
on:
  push:
    branches: [master]
    paths-ignore:
      - "README.md"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare source file
        run: |
          sudo apt-get -y update && sudo apt-get install -y bsdmainutils
          echo "\`\`\`" > inject_version_file
          cat version | column -s "=" -t >> inject_version_file
          echo "\`\`\`" >> inject_version_file
      - name: Update README.md file
        uses: unfor19/replacer-action@v1.0.3
        with:
          src-file-path: "inject_version_file"
          dst-file-path: "README.md"
          start-value: "<!-- replacer_start -->"
          end-value: "<!-- replacer_end -->"
          git-user-name: "Replacer GitHub Action"
          git-user-email: "githubactions@meirg.co.il"
          git-commit-msg: "Updated by GitHub Actions"
          git-skip-commit: false
          git-skip-push: false
          create-backup: false
